### ISSUE TITLE
cms block, get by identifier and 

### ISSUE THREAD

**Issue by lsv** [magento/graphql-ce#635] opened 2019-04-29 11:50 UTC
### Preconditions (*)

1. Magento 2.3.2

### Steps to reproduce (*)

1. Create atleast 2 store views
2. Create 2 cms blocks, with the same identifier,  set storeview scope two the 2 different store views created at the top
3: Get the cms block with the identifier - it will ALWAYS get the cms block from the default webstore.
4: (You can check with `storeConfig: { code }` that you actually are running with a different scope.

My current setup 

![Screenshot from 2019-04-29 13-45-18](https://user-images.githubusercontent.com/20708/56894088-178fb780-6a85-11e9-9c58-0c67af394cfc.png)

### Expected result (*)

1. The content from the cms block with the content from the scoped cms block

### Actual result (*)

1. Always the default cms block, properly actually the first element found in the database with the cms block identifier.

From my current setup (see screenshot above) when I run the following graphql

```
{
  storeConfig {
    code
  }
  cmsBlocks(identifiers: "footer-block-one") {
    items {
      content
    }
  }
}
```

I get this result

```
{
  "data": {
    "storeConfig": {
      "code": "english"
    },
    "cmsBlocks": {
      "items": [
        {
          "content": "<p>Danish</p>"
        }
      ]
    }
  }
}
```

Where the content should be english

3: If you disable the first cms block (the Danish one in my above setup), you will be thrown a `NotFoundException`, even though the english cms block still is enabled.

```
https://github.com/magento/graphql-ce/blob/2.3-develop/app/code/Magento/CmsGraphQl/Model/Resolver/DataProvider/Block.php#L51
```

A storeview code should be added around here

**Comment by naydav** [comment] 2019-05-03 20:54
@TomashKhamlai 
Please, verify this issue

**Comment by GovindaSharma** [comment] 2019-05-04 08:17
#dmcdindia1

**Comment by GovindaSharma** [comment] 2019-05-04 08:17
i am working on this

**Comment by TomashKhamlai** [comment] 2019-05-06 11:15
Just a little note:
It is possible to get
```graphql
    "storeConfig": {
      "code": "english"
    }
```
only if the `code` for Default Store View was renamed from "default" to "english" or  "english" is the second Store View and was set as default Store View for the Store. I haven't check the conditions when the main website was removed.

**Comment by TomashKhamlai** [comment] 2019-05-06 12:52
@lsv could you share your experience of using `storeConfig`?

I am not familiar with this part of GraphQL functionality and I have one question about your expectations. I suspected that you have expectations that if the `cmsBlocks` refers to the Store View other than the one that is "default" then the query `storeConfig` should be smart enough to display the context of the operation... Am I right?

**Comment by lsv** [comment] 2019-05-06 22:30
In your HTTP header you can add your store code to a Store variable.
Which is also [documented](https://devdocs.magento.com/guides/v2.3/graphql/send-request.html)

If not specified "default" store code will be used

And therefor none of the stores should be found, and I think magento will throw a store not found exception. Though im pretty sure that you set your default store via the index.php SERVER (MAGE_RUN_CODE) variable, otherwise everything will blow :) - If not Magento actually just picks the first store found.

**Comment by TomashKhamlai** [comment] 2019-05-08 16:39
@lsv, I am sorry but this issue is not reproducible anymore on the latest 2.3-develop branch. Please tell us which distribution of Magento did you use: composer or git checked out by tag? I opened another issue: #691 
Could you recheck your steps? Don't you mind to read my issue and check if it is relative to your issue?

**Comment by TomashKhamlai** [comment] 2019-06-11 14:23
# Reproduced cases
After moderation of the ticket description, the problem seems to be clear now

## Case 1. 
### Preconditions
 - 	3 Websites with 1 Store and 1 Store View each
 -	2 CMS blocks assigned to non-default Store View

### Assertions

#### Request
```graphql
{
  storeConfig {
    code
  }
  cmsBlocks(identifiers: "footer-block-one") {
    items {
      content
    }
  }
}
```

#### Headers
Do not send. the default will be used under the hood.

#### Response
```graphql
{
  "data": {
    "storeConfig": {
      "code": "default"
    },
    "cmsBlocks": {
      "items": [
        {
          "content": "<p>2.&nbsp;</p>"
        }
      ]
    }
  }
}

:x: `code` works as expected. But generally, it is a failure.

## Case 2
### Preconditions
 - 	3 Websites with 1 Store and 1 Store View each
 -	2 CMS blocks assigned to non-default Store View

### Assertions

#### Request
```graphql
{
  storeConfig {
    code
  }
  cmsBlocks(identifiers: "footer-block-one") {
    items {
      content
    }
  }
}
```

#### Headers
```graphql
{"Store": "default"}
```

#### Response
```graphql
{
  "data": {
    "storeConfig": {
      "code": "default"
    },
    "cmsBlocks": {
      "items": [
        {
          "content": "<p>2.&nbsp;</p>"
        }
      ]
    }
  }
}
```

:x: `code` works as expected. But generally, it is a failure.

## Case 3
### Preconditions
 - 	3 Websites with 1 Store and 1 Store View each
 -	2 CMS blocks assigned to non-default Store View

### Assertions

#### Request
```graphql
{
  storeConfig {
    code
  }
  cmsBlocks(identifiers: "footer-block-one") {
    items {
      content
    }
  }
}
```

#### Headers
```graphql
{"Store": "sstv"}
```

#### Response
```graphql
{
  "data": {
    "storeConfig": {
      "code": "default"
    },
    "cmsBlocks": {
      "items": [
        {
          "content": "<p>2.&nbsp;</p>"
        }
      ]
    }
  }
}
```

:heavy_check_mark: Works as Expected

## Case 4
### Preconditions
 - 	3 Websites with 1 Store and 1 Store View each
 -	2 CMS blocks assigned to non-default Store View

### Assertions

#### Request
```graphql
{
  storeConfig {
    code
  }
  cmsBlocks(identifiers: "footer-block-one") {
    items {
      content
    }
  }
}
```

#### Headers
```graphql
{"Store": "tstv"}
```

#### Response
```graphql
{
  "data": {
    "storeConfig": {
      "code": "tstv"
    },
    "cmsBlocks": {
      "items": [
        {
          "content": "<p>2.&nbsp;</p>"
        }
      ]
    }
  }
}
```

:x: `code` works as expected. But generally, it is a failure.

**Comment by TomashKhamlai** [comment] 2019-06-21 18:50
Closing this because #691 has more problems described and steps shows more details

**Closed as completed by TomashKhamlai** 2019-06-21 18:50 UTC
Labels: bug, good first issue, Contribution Day, Component: CmsGraphQl
