### ISSUE TITLE
is_anchor not working correctly

### ISSUE THREAD

**Issue by PiotrSzlagura** [magento/graphql-ce#91] opened 2018-06-11 09:57 UTC
### Preconditions

1. Create clean Magento 2.3 installation
2. Install test data from repo

### Steps to reproduce

1. Execute graphql query:
```graphql
{
    category(id: 21) {
        products {
            total_count
            items {
                name
            }
        }
    }
}
```

### Expected result

1. Query should return list of products that are in children categories of `21`, because all of them have `is_anchor` set to true.

### Actual result

1. Query returns empty array.

By the way, I have also checked receiving data using REST api, and when I executed:
`/rest/V1/categories/21/products` it returned list of products from children categories.

**Comment by paliarush** [comment] 2018-06-11 18:30
@PiotrSzlagura thank you for reporting the issue. It is, however, a duplicate of:
- Products cannot be fetched in parent/anchor category #89

**Closed as completed by paliarush** 2018-06-11 18:30 UTC
Labels: duplicate
