### ISSUE TITLE
Links to the downloadable_product_links are direct links

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#729] opened 2019-06-03 13:49 UTC
### Preconditions (*)

1. #412 is merged

### Steps to reproduce (*)

1. query products
```graphql
{
  products(
    search: "down"
    filter: {
      sku: {
        eq: "Downloadable Product 1"
      }
    }
  ) {
    items {
      type_id
      sku
      name

      ... on DownloadableProduct {
        downloadable_product_samples {
          sample_file
          sample_type
          title
        }
        downloadable_product_links {
          sample_file
          sample_type
          sample_url
        }
      }
    }
    total_count
  }
}
```

### Expected result (*)

1. Response:
```graphql
{
  "data": {
    "products": {
      "items": [
        {
          "type_id": "downloadable",
          "sku": "Downloadable Product 1",
          "name": "Downloadable Product 1",
          "downloadable_product_samples": [
            {
              "sample_file": "https://graphql-ce.io/downloadable/download/sample/sample_id/1/",
              "sample_type": "FILE",
              "title": "Trailer #1"
            },
            {
              "sample_file": "https://graphql-ce.io/downloadable/download/sample/sample_id/2/",
              "sample_type": "FILE",
              "title": "Trailer #2"
            }
          ],
          "downloadable_product_links": [
            {
              "sample_file": "https://graphql-ce.io/downloadable/download/sample/sample_id/{SOME_ID}/",
              "sample_type": "FILE",
              "sample_url": null
            },
            {
              "sample_file": null,
              "sample_type": "URL",
              "sample_url": "https://google.com"
            }
          ]
        }
      ],
      "total_count": 1
    }
  }
}
```

### Actual result (*)

1. Response:
```graphql
{
  "data": {
    "products": {
      "items": [
        {
          "type_id": "downloadable",
          "sku": "Downloadable Product 1",
          "name": "Downloadable Product 1",
          "downloadable_product_samples": [
            {
              "sample_file": "https://graphql-ce.io/downloadable/download/sample/sample_id/1/",
              "sample_type": "FILE",
              "title": "Trailer #1"
            },
            {
              "sample_file": "https://graphql-ce.io/downloadable/download/sample/sample_id/2/",
              "sample_type": "FILE",
              "title": "Trailer #2"
            }
          ],
          "downloadable_product_links": [
            {
              "sample_file": "/2/0/2019-06-03_16-32.png",
              "sample_type": "FILE",
              "sample_url": null
            },
            {
              "sample_file": null,
              "sample_type": "URL",
              "sample_url": "https://google.com"
            }
          ]
        }
      ],
      "total_count": 1
    }
  }
}
```

**Comment by naydav** [comment] 2019-06-12 18:25
Duplicate of https://github.com/magento/graphql-ce/issues/710

**Closed as completed by naydav** 2019-06-12 18:25 UTC
Labels: bug, good first issue, Component: DownloadableGraphQl
