### ISSUE TITLE
Separate cart items are created instead of quantity increment

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#793] opened 2019-07-29 12:58 UTC
... and update of the last cart-items discards an update that was applied to the first cart-item. Cart-items are never joined together.

Related to #699

The cart is not updating properly: new cart items are created instead of changing quantity while adding the same product to the cart. At the same time update of the first cart-item do not trigger recalculation while update of the last one joins them back together.

Note: could be specific to customizable_options

https://github.com/magento/graphql-ce/pull/699/commits/c7d9130289993310992cb3e4a0b5ec7c3dd196bd

### Preconditions (*)

1. Create a configurable product with a customizable option that is not required
![2019-07-29-16-02-graphql-ce loc](https://user-images.githubusercontent.com/11827230/62051830-e312cf80-b21c-11e9-91de-efcf65c1e9da.png)

2. Add this product to cart via `addConfigurableProductsToCart`. Specify that **package** is `D` and **quantity** is `1` 
3. Change **quantity** to `2` via `updateCartItems`
4. Add this product to cart via `addConfigurableProductsToCart`. Specify that **package** is `D` and **quantity** is `3` (repeat what was done in step 2 without any changes. Even quantity is updated it is still the same cartItem)
5. Verify that your cart contains 2 cart items. Stop reproducing here if your information differs. For example:
```graphql
{
  "data": {
    "updateCartItems": {
      "cart": {
        "items": [
          {
            "id": "27",
            "quantity": 1
          },
          {
            "id": "29",
            "quantity": 3
          }
        ]
      }
    }
  }
}
```

### Steps to reproduce (*)

1. Update the first item
```graphql
mutation {
  updateCartItems(input: {
    cart_id: "X9klnJz5K840LhG22VeJPvoOnHFZ6KsZ"
    cart_items: {
      cart_item_id: 27
      quantity: 4
      
    }
  }) {
    cart {
      items {
        id
        quantity
      }
    }
  }
}
```

My result was:
```graphql
{
  "data": {
    "updateCartItems": {
      "cart": {
        "items": [
          {
            "id": "27",
            "quantity": 4
          },
          {
            "id": "29",
            "quantity": 3
          }
        ]
      }
    }
  }
}
```
2. Update last item
```graphql
mutation {
  updateCartItems(input: {
    cart_id: "X9klnJz5K840LhG22VeJPvoOnHFZ6KsZ"
    cart_items: {
      cart_item_id: 29
      quantity: 4
      
    }
  }) {
    cart {
      items {
        id
        quantity
      }
    }
  }
}
```

### Expected result (*)

1. Predictive behavior
2. Quantity increment for the request with the same product
3. Changes to one item do not have an impact on another item

### Actual result (*)

1. 
```graphql
{
  "data": {
    "updateCartItems": {
      "cart": {
        "items": [
          {
            "id": "27",
            "quantity": 1
          },
          {
            "id": "29",
            "quantity": 4
          }
        ]
      }
    }
  }
}
```

**Comment by Rus0** [comment] 2019-08-28 15:47
Duplicate of #792

**Closed as completed by Rus0** 2019-08-28 15:47 UTC
Labels: bug
