### ISSUE TITLE
GraphQL doesn't check that Region belongs to country where it is possible

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#1046] opened 2019-11-01 14:21 UTC
### Problem:
1. In Canada, there is no California. Send request:
```graphql
mutation {
  createCustomerAddress(
    input: {
      firstname: "Yes"
      lastname: "Yes"
      country_code: CA
      region: {
        region: "California"
      }
      postcode: "Yes"
      city: "Yes"
      street: "Yes"
      telephone: "Yes"
    }
  ) {
    firstname
    telephone
    region {
      region
      region_code
    }
    lastname
    country_code
    postcode
  }
}
```
Response: 
```graphql
{
  "data": {
    "createCustomerAddress": {
      "firstname": "Yes",
      "telephone": "Yes",
      "region": {
        "region": "California",
        "region_code": null
      },
      "lastname": "Yes",
      "country_code": "CA",
      "postcode": "Yes"
    }
  }
}
```
2. Login as a Customer and check addresses in Address Book
![image](https://user-images.githubusercontent.com/11827230/68030878-1b65f600-fcc3-11e9-9704-0c12b664ace5.png)
3. Click **Edit**
:x: California is not selected
![image](https://user-images.githubusercontent.com/11827230/68031021-6849cc80-fcc3-11e9-8e33-13b98b8092aa.png)
4. :x: Modify **Company** and click "Save Address" button
![image](https://user-images.githubusercontent.com/11827230/68031098-9c24f200-fcc3-11e9-8042-eb25b6d1e293.png)
 

### Proposed solution:
Use \Magento\Customer\Model\Address\Validator\Country::validate for this purpose.

**Comment by lenaorobei** [comment] 2019-11-08 17:53
@TomashKhamlai please check on latest `2.3-develop`. It should be fixed.

**Comment by TomashKhamlai** [comment] 2019-11-11 15:15
@lenaorobei, no it is not fixed yet.

**Comment by atwixfirster** [comment] 2019-12-16 22:37
Unable to reproduce.

Steps taken:
**1.** Create an empty cart:

```
mutation {
  createEmptyCart
}
```

**2.** Add product into cart:
```
mutation {  
  addSimpleProductsToCart(
    input: {
      cart_id: "hnnNHI6X7a3N6cdbmoeswrF3qewwHQqC"
      cart_items: [
        {
          data: {
            quantity: 1
            sku: "xxx0001"
          }
        }
      ]
    }
  ) {
    cart {
      items {
        id
        product {
          sku
          stock_status
        }
        quantity
      }
    }
  }
}
```

**3.** Set shipping address:
```
mutation {
  setShippingAddressesOnCart(
    input: {
      cart_id: "hnnNHI6X7a3N6cdbmoeswrF3qewwHQqC"
      shipping_addresses: [
        {
          address: {
            firstname: "John"
            lastname: "Doe"
            company: "Company Name"
            street: ["320 N Crescent Dr", "Beverly Hills"]
            city: "Los Angeles"
            region: "CA"
            postcode: "90210"
            country_code: "CA"
            telephone: "123-456-0000"
            save_in_address_book: false
          }
        }
      ]
    }
  ) {
    cart {
      shipping_addresses {
        firstname
        lastname
        company
        street
        city
        region {
          code
          label
        }
        postcode
        telephone
        country {
          code
          label
        }
        
      }
    }
  }
}
```

**Actual result:** `Region is not available for the selected country`:

<img width="989" alt="1046" src="https://user-images.githubusercontent.com/13585327/70949007-71211280-2065-11ea-983d-9b64c2c41bac.png">

**Closed as completed** 2019-12-18 19:24 UTC
Labels: bug, for-grooming, Component: QuoteGraphQl
