### ISSUE TITLE
Internal Server Error when requesting the selected_payment_method property

### ISSUE THREAD

**Issue by dplaton** [magento/graphql-ce#865] opened 2019-08-28 06:21 UTC
### Preconditions (*)

1. Magento 2.3.2
2. PHP 7.2

### Steps to reproduce (*)

1. Using your favorite GraphQL client, create an empty guest cart
2. Query the cart details (the `selected_payment_method` property should suffice):
```
query {
  cart(cart_id: "OURbOitmbVfZp5wHElTlObTMjvFxOrJN") {
   selected_payment_method {
    code
  }
  }
}
```

### Expected result (*)

1. The query should work and the result should be an empty string:
```
{
  "data": {
    "cart": {
      "selected_payment_method": {
        "code": ""
      }
    }
  }
}
```

### Actual result (*)

1. There is an `Internal Server Error` response
```
{
  "errors": [
    {
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 3,
          "column": 4
        }
      ],
      "path": [
        "cart",
        "selected_payment_method"
      ]
    }
  ],
  "data": {
    "cart": {
      "selected_payment_method": null
    }
  }
}
```

This error occurs on our cloud instance with the environment I described above. I couldn't reproduce this error using a local Magento instance which is running on the [kubernetes devbox](https://github.com/magento/magento2-kubernetes-devbox/tree/master/etc)

**Comment by TomashKhamlai** [comment] 2019-08-28 08:58
Couldn't reproduce by provided steps. A similar issue was there in the cart query #758 but it is fixed now. My environment is PHP 7.2.19, Magento 2.3-develop from git.

Please try to follow your steps again but switch to developer mode first.
`php bin/magento deploy:mode:set developer`

Post the response that you will get after doing this.

**Comment by dplaton** [comment] 2019-08-28 10:50
Thanks for your reply, @TomashKhamlai 
Unfortunately, I cannot switch developer mode, since this is our cloud instance. That instance is running 2.3.2 (so no "develop" branch for us)

**Comment by TomashKhamlai** [comment] 2019-08-28 12:23
@dplaton, I will be glad if the next information can help you.
This repository https://github.com/magento/magento-cloud-docker provides a dockerized environment for playing with Magento cloud. There are some instructions here https://devdocs.magento.com/guides/v2.3/cloud/docker/docker-config.html that can help you. For example `./vendor/bin/ece-tools docker:build --mode="developer"`. You need to have some basic skills with docker.

**Comment by mhaack** [comment] 2019-08-29 08:06
Hi @TomashKhamlai I'm working on this together with @dplaton. We tested as you suggested with the local Magento Cloud environment with developer mode enabled:
```
docker-compose run deploy magento-command deploy:mode:show                                                                               
...
[ ok ] Starting enhanced syslogd: rsyslogd.
Current application mode: developer. (Note: Environment variables may override this value.)
```

Reproducing with the steps above the debug message I get is different than in #758 :
```
{
  "errors": [
    {
      "debugMessage": "The payment method you requested is not available.",
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 3,
          "column": 4
        }
      ],
      "path": [
        "cart",
        "selected_payment_method"
      ]
    }
  ],
  "data": {
    "cart": {
      "selected_payment_method": null
    }
  }
}
```

**Comment by TomashKhamlai** [comment] 2019-08-29 08:55
Great to hear that it works for you! :1st_place_medal:
I haven't tried it yet).

Create a patch from the PR linked below and apply to your instance. If there will be some troubles, please create a ticket to support team. Reopen this ticket if the problem will be reproducible after applying a patch in any of your environments.
 
#665

**Closed as completed by TomashKhamlai** 2019-08-29 08:55 UTC
Labels: bug, Component: QuoteGraphQl
